---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knative-serving

resources:
  - ../../base/knative-serving

patches:
  - target:
      kind: KnativeServing
      name: knative-serving
    patch: |-
      - op: add
        path: /spec/ingress
        value:
          kourier:
            enabled: true
  - target:
      kind: KnativeServing
      name: knative-serving
    patch: |-
      - op: add
        path: /spec/config
        value:
          network:
            ingress-class: "kourier.ingress.networking.knative.dev"
